### ISSUE TITLE
Views configs missing

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/project#1]
For releases, its still trying to use `hook_views_default_views()`, No config file for the views. I suppose that's why the link to 'View all releases' not working.
The link to 'Administer releases' also doesnt list any releases even after adding releases.
Glad to see this getting going though.

**Comment by quicksketch** [comment]
Thanks, I just saw this issue! These issues have been resolved since this was filed. Fixed mostly in f5b1e2c7edc7bb04c2f16d6f8db66ec4af903362, but followups have expanded the Views integration.
