### ISSUE TITLE
Add project information via hook_fields_extra_fields().

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/project#16]
I'm going to add the github links into both the node->content and as a block, so that the site builder can choose to display them either as a psuedo-field, or via layouts. The PR also adds usage data to the node for display.

**Comment by jenlampton** [comment]
I'm expanding this issue to include the information added by project module into the node too. If we could set weights for everything via the UI it will be a better experience for everyone involved :)

**Comment by quicksketch** [comment]
Looks good! Merged into 1.x-1.x. Thanks!
