### ISSUE TITLE
Remove "Statistics" as a reserved project name

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/project#20]
Project.module, line 607, prevents me releasing my port of Statistics module.

```
  // Make sure machine name isn't already in use, or reserved.  Includes all
  // X from project/issues/X paths used in project_issues module
  $reserved_names = array('user', 'issues', 'releases', 'rss', 'subscribe-mail', 'search', 'add', 'update_project', 'statistics', 'comments', 'autocomplete', 'cvs', 'developers', 'usage');
```

Assuming leftover from D7 from when Statistics was in core. If there isn't another good reason can we remove "statistics" from that line please? I'd hate to have to rename; that module is big.

Edit: figured it out: according to the comment above 

> Includes all X from project/issues/X paths used in project_issues module

The D6 version of `project_issues` module had a menu entry for `'project/issues/statistics'` and `'project/issues/update_project'`. Gone since D7, so safe to remove I'd suspect.

**Comment by quicksketch** [comment]
Thanks, removed it from being a reserved module name.
