### ISSUE TITLE
project_usage_get_project_total_usage() doesnt work

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/project#3]
`$node_type->settings['project_release_api_versions']` is always NULL; I dont see where this is set for any other node type but releases. (the function would probably give a return for releases then, but its suposed to be for project_xx nodes, isn;t it?).
@quicksketch tagging since project issues may be a bit far down.

**Comment by quicksketch** [comment]
I think the setting of `$node_type->settings['project_release_api_versions']` is correct; it indeed should only be present on "release" types, not on the parent project types. I think what needs to be done here is the project type's setting for release type needs to be retrieved first.

Something like this:

``` php
  $release_node_type_name = $project_node_type->settings['project_release_type'];
  if ($release_node_type_name) {
    $release_node_type = node_type_get_type($release_node_type_name);
    $api_versions = $release_node_type->settings['project_release_api_versions'];
    // Existing code for getting usage per API version.
  }
```

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/project/issues/4. Long time coming.
