### ISSUE TITLE
[DX] Change project node links to #type = link instead of markup

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/project#31]
In the `project_release_node_view()` function the links added to the content of a node are added as `#markup` elements. This makes it really hard to add classes to the links provided, in your theme, for example.

If these were instead `#link` elements, it would be easy to alter in `#attributes` as needed.

**Comment by quicksketch** [comment]
Thanks, sounds good and it's an easy change. Merged in https://github.com/backdrop-contrib/project/pull/32.
