### ISSUE TITLE
Hash IP addresses when tracking project usage

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/project#39]
From @jenlampton in https://github.com/backdrop/backdrop-issues/issues/3688:

This is a follow-up to #3168 which I think will replace the need for that issue entirely.

From my comment:

> I think the only real issue here is that we are sending an IP address so that we can tell all the sites apart. Why don't we just hash the IP address so that no recognizable data is ever stored?

I'm not sure if this is an issue that needs to go against core, project module, or b.org, but we should be able to move this issue when we decide where it should go :)

**Comment by quicksketch** [comment]
I think this is a good idea. Interesting, I went to check why this was in the first place and `project_usage.install` includes this description on the DB column:

```
      'hostname' => array(
        'description' => 'The IP address of the incoming request (to detect possible abuse).',
```

I'm guessing the thinking there is that any abusive IP addresses would then be blocked. That said, I think if we wanted to block abuse, we could do it in software in front of Backdrop (such as a CDN or abuse blocking service with a proxy). So I don't think project module is the right place to track this information and including it is only a liability and privacy concern in our code base.

**Comment by quicksketch** [comment]
I filed a PR for this: https://github.com/backdrop-contrib/project/pull/40

Rather than make a new hashing algorithm, I reused the hashing we use on passwords, since that's probably already the most secure hashing we have available.

**Comment by jenlampton** [comment]
If/when we do get autoban in core, we can also check the IP before it's
hashed, and not save the hashed data if it matches an abusive IP or is in a
range of blocked IPs. By the time were saving usage data for that site it
should have passed all the checks anyway.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/project/pull/40.
