### ISSUE TITLE
Missing 'administer projects' permission

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/project#41]
I see a lot of references to the 'administer projects' permission, but I can't see it set/created anywhere...

**Comment by jenlampton** [comment]
The permission definitely exists in [the Drupal 7 version](https://git.drupalcode.org/project/project/-/blob/7.x-2.x/project.module#L450).

It looks like the Backdrop version is missing the whole `project_permission()` hook. How did this even work without it?

**Comment by herbdool** [comment]
The PR looks good to me. It's odd that this wasn't included in the port. I can imagine that it still worked because for most actions it was just user 1, or it was github webhooks which might not have needed those permissions.

I looked at the history of the project.module and seems like it didn't retain the commit history from Drupal so I guess we won't know why (unless @quicksketch remembers).

**Comment by jenlampton** [comment]
Yeah, you probably also saw the other issue to fix that? I spent some time on it last week... it's tricky as so much changed between the last Drupal commit and the first one in this repo.

**Comment by ghost** [comment]
> The PR looks good to me.

Me too. I tested it in relation to https://github.com/backdrop-ops/backdropcms.org/issues/516 and it fixed the problem.

@jenlampton Can we get this merged and a new version released so we can fix https://github.com/backdrop-ops/backdropcms.org/issues/516?

**Comment by jenlampton** [comment]
Wearing my bug-squad hat I can merge the PR (in two weeks), but we are not authorized to make a new release. We'll need to ping @quicksketch for that (and maybe a faster merge?)

**Comment by ghost** [comment]
Ah sorry, for some reason I thought you were the maintainer @jenlampton :smile:

**Comment by jenlampton** [comment]
Patch applied, tested, and deployed.

**Comment by jenlampton** [comment]
> Wearing my bug-squad hat I can merge the PR (in two weeks)

I'm merging the PR today. I'm counting the comment above from @BWPanda `The PR looks good to me.` as an RTBC status, hope that's okay? (I see this project was created before the issue labels were copied from our master.)
