### ISSUE TITLE
Adding Telemetry 

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/project#51]
We have been working on getting telemetry into Backdrop CMS core and the current plan is to collect and maintain that data on Backdropcms.org

See: 

* https://github.com/backdrop/backdrop-issues/issues/285
* https://github.com/backdrop-ops/backdropcms.org/wiki/Telemetry-Initiative

Currently, @quicksketch has added code to the project module for testing. So, I am opening this issue simply to track the role that the project module will likely play in this initiative. 

Not sure yet if I should report issues in the dev version of the project module here or in the telemetry issue.

**Comment by quicksketch** [comment]
This is now fixed in https://github.com/backdrop-contrib/project/pull/50. Most all of the discussion for Telemetry has been happening in the core issue Tim noted above.
